---
- name: Check disk usage
  hosts: all
  tasks:
    - name: Display disk usage
      command: df -h
      register: disk_usage

    - name: Show disk usage output
      debug:
        var: disk_usage.stdout
